# Generated by Django 2.2.7 on 2019-11-27 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Redactor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=99)),
                ('apellido', models.CharField(default='', max_length=99)),
            ],
        ),
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titular', models.CharField(default='', max_length=100)),
                ('entradilla', models.TextField()),
                ('noticia', models.TextField()),
                ('fecha', models.DateField()),
                ('redactor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appE1.Redactor')),
            ],
        ),
    ]
