# Generated by Django 2.2.7 on 2019-11-25 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appE1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='fecha',
            field=models.CharField(default='', max_length=20),
        ),
    ]
