# Generated by Django 2.2.7 on 2019-11-25 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appE1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=99)),
                ('apellido', models.CharField(default='', max_length=99)),
            ],
        ),
        migrations.RenameField(
            model_name='articulo',
            old_name='cuerpo',
            new_name='noticia',
        ),
        migrations.AddField(
            model_name='articulo',
            name='autor',
            field=models.ForeignKey(default='Director', on_delete=django.db.models.deletion.CASCADE, to='appE1.Autor'),
        ),
    ]
