# Generated by Django 2.2.7 on 2019-11-25 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appE1', '0003_auto_20191126_0050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='titular',
            field=models.CharField(default='', max_length=100),
        ),
    ]
