# Generated by Django 2.2.7 on 2019-11-25 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appE1', '0004_auto_20191125_1738'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articulo',
            old_name='autor',
            new_name='redactor',
        ),
    ]
