# Generated by Django 2.2.7 on 2019-11-25 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appE1', '0005_auto_20191125_1741'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articulo',
            name='redactor',
        ),
    ]
